### ISSUE TITLE
bug: original managed IP cannot be deleted with 2 or more managed IPs present

### ISSUE THREAD

**Issue by TBT-TBT** [dec0dOS/zero-ui#12]
# Bug Report

**ZeroUI version:**

latest

**Current behavior:**

In the "members" area of a network, the first given "managed IP" cannot be deleted, even if one or more further IPs are in the managed IPs list.

e.g:
172.30.36.203 (first managed IP)
172.30.36.204 (additional IP)
172.30.36.205 (additional IP)

bug: 172.30.36.203 cannot be deleted

**Expected behavior:**

deletion of first IP possible after at least a second IP is added:

172.30.36.203 (first managed IP)
172.30.36.204 (additional IP)

--> 172.30.36.203 should be allowed to delete, after deletion 172.30.36.204 should not be able to delete.

**Steps to reproduce:**

add further IPs to a member, try to delete the first IP.

**Comment by dec0dOS** [comment]
Yes, that is the web application bug, it should be fixed. Thanks for reporting, I'll try to look into it.

**Comment by TBT-TBT** [comment]
Regarding the Github bot: the bug is still there.

**Comment by knightian** [comment]
Yep encountered this today

**Comment by techroy23** [comment]
Bug still present fresh install on docker compose 2.1.1, ubuntu 20.04

**Comment by techroy23** [comment]
Update :
I was able to remove the assigned IP by
1a.) Clicking forget in the client
2.) De-auth client in UI
3.) Delete client in UI
4.) Manually add the client in UI
5.) Add the desired IP first before checking the box to authorize.
6.) Enter network ID in Client.

**Comment by TBT-TBT** [comment]
> Update : I was able to remove the assigned IP by 1a.) Clicking forget in the client 2.) De-auth client in UI 3.) Delete client in UI 4.) Manually add the client in UI 5.) Add the desired IP first before checking the box to authorize. 6.) Enter network ID in Client.

Well, that is a workaround, but no bugfix / normal behaviour. ZT Central allows that without anything special.

**Comment by drtech981** [comment]
Still having this issue a fresh install on Ubuntu 20.04 Docker Version 20.10.11, any updates ?

**Comment by drtech981** [comment]
Issue still persists in zero-ui:1.1.5 docker image. Original IP cannot be removed even if other IPs are manually added.

**Comment by dec0dOS** [comment]
Did you really update the image? It works fine for me now. You could check the member settings for "Tags and Caps" feature, it was added in the 1.1.0 release.

<img width="376" alt="Снимок экрана 2021-12-17 в 15 45 12" src="https://user-images.githubusercontent.com/14824142/146546691-006b6876-e49c-42ff-b79b-741dc7eeb3fd.png">

In the future after few changes you could check the version number in the UI itself.

**Comment by TBT-TBT** [comment]
I can confirm that the issue is indeed solved with the tag :latest (auto update with Watchtower).

Thank you very much, @dec0dOS ! I appreciate this bugfix very much and can now really switch to Zero-UI for my Controller, as I can now model my networks with the IP addresses as they are on MyZT.com.

**Comment by drtech981** [comment]
@dec0dOS Yes, I can see tags and capabilities in the added options field for each client. Even today I repulled the latest image and the issue still persists. 
If I join a client by entering the network address, as soon as I Authorize it, it gets an IP assigned automatically which cannot be deleted even if additional IPs are assigned.

The only way to circumwent this is to first add the memer ID to the controller, assign the IPs, then authorize the client and then finally enter the network address in the clients Zerotier One UI/CLI.

**Comment by TBT-TBT** [comment]
It definitely works. Let the member apply for a join, auth the member, add a second IP manually, with the last position of your choosing, press "+". You will see 2 IPs on the client side. Then remove the autoassigned IP. BINGO!

**Comment by bodleytunes** [comment]
> Did you really update the image? It works fine for me now. You could check the member settings for "Tags and Caps" feature, it was added in the 1.1.0 release.
> 
> <img alt="Снимок экрана 2021-12-17 в 15 45 12" width="376" src="https://user-images.githubusercontent.com/14824142/146546691-006b6876-e49c-42ff-b79b-741dc7eeb3fd.png">
> 
> In the future after few changes you could check the version number in the UI itself.

Hi,

Not sure if I'm missing something but I'm trying to upgrade and I'm not seeing those new tag features?

I've changed the tag in the docker-compose file and pulled, rebuilt and restarted and everything is the same.

Cheers,
Jon.

**Comment by dec0dOS** [comment]
@bodleytunes that is strange. Try to clean the browser cache (or use another browser).

**Comment by bodleytunes** [comment]
the same using new browser edge, create new network joined a user, same stuff.  I'm using tag 1.1.0 not 1.1.5 ? which one is the latest?

**Comment by bodleytunes** [comment]
assuming 1.1.5 ?

**Comment by dec0dOS** [comment]
Yeah, 1.1.5

**Comment by bodleytunes** [comment]
will try

**Comment by bodleytunes** [comment]
<img width="273" alt="image" src="https://user-images.githubusercontent.com/619239/146584872-71a43648-4001-4c47-be38-ce8821fcccae.png">

**Comment by bodleytunes** [comment]
Just rebuilt from scratch using new docker volumes and still the same
<img width="360" alt="image" src="https://user-images.githubusercontent.com/619239/146587728-cbe443de-e934-4baf-8b50-77c6f55d49b0.png">

**Comment by bodleytunes** [comment]
And cleared browser cache

**Comment by dec0dOS** [comment]
Try the "latest" tag

**Comment by bodleytunes** [comment]
sorted, I had to delete a load of old images and rebuild everything from scratch then it worked.  👍🏻

**Comment by TBT-TBT** [comment]
Guys, it works. Definitely. If it doesn't on your end, the problem is on your end. So please don't make @dec0dOS fix your problems, he did a great job fixing this bug.

**Comment by drtech981** [comment]
@TBT-TBT I did a reinstall of the zero-ui and the controller, and now delete IP option is working fine ! Thanks @dec0dOS for this awesome project !
